
name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build application
      run: npm run build
    
    - name: Build Docker image
      run: docker build -t company-chat-app:${{ github.sha }} .
    
    - name: Tag as latest
      run: docker tag company-chat-app:${{ github.sha }} company-chat-app:latest
    
    # Add your container registry push steps here
    # Example for Docker Hub:
    # - name: Push to Docker Hub
    #   run: |
    #     echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    #     docker push company-chat-app:${{ github.sha }}
    #     docker push company-chat-app:latest
